baseURL: "https://khouryjoseph.com/"
title: Joseph Khoury
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

params:
    description: "I am a PhD Candidate in Computer Science and Engineering at Louisiana State University (LSU)."
    author: Joseph Khoury
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Joseph Khoury
          subtitle: "<div style='text-align: justify; text-justify: inter-word;'>I'm a Ph.D. candidate in Computer Science and Engineering specializing in Cybersecurity at Louisiana State University (LSU).

          <br><br>
          My research interests encompass a range of critical areas within cybersecurity. These include Internet-scale measurements, utilizing both passive and active techniques to effectively identify and combat malicious cyber activities. Additionally, I focus on the application of advanced machine learning techniques, specifically Temporal Graph Neural Networks (TGNNs), to detect Advanced Persistent Threats (APTs) at both the network and host levels. I also investigate the use of Large Language Models (LLMs) to uncover vulnerabilities in source and binary code, contributing to the development of more secure software systems. Lastly, I am actively involved in the creation of cyber defense training materials tailored for cyber forces. By conducting translational research, I aim to bridge the gap between theoretical knowledge and practical applications, ensuring that the insights gained from my work directly benefit the security of nations and their citizens.
          <br><br>
          Before coming to LSU, I was a Graduate Research Assistant at the Cyber Center for Security and Analytics (CCSA) at the University of Texas at San Antonio. I received a Bachelor’s degree from the Holy Spirit University of Kaslik (USEK) and a Master’s degree from the American University of Beirut (AUB), both in Computer Science.</div>"
          imageUrl: "/JosephKhoury-v2.jpg"
          imageWidth: 180
          imageHeight: 180
          imageTitle: Joseph Khoury

    socialIcons:
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=pupjXigAAAAJ&hl=en&oi=ao
        - name: linkedin
          url: https://www.linkedin.com/in/joseph-khoury-313a55125/
        - name: Email
          url: mailto:jkhour5@lsu.edu
    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: false
    label:
      text: "Joseph Khoury"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
