baseURL: "https://khouryjoseph.com/"
title: Joseph Khoury
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: false

disableKinds:
  - robotsTXT
  - sitemap
  - taxonomy

params:
    description: "Computer Scientist | Cybersecurity Research"
    author: Joseph Khoury
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
        enabled: true
        title: Joseph Khoury
        subtitle: "<div style='text-align: justify; text-justify: inter-word;'>

        <span style='color:#000000;font-weight: bold;'>
        &#x2757; I am currenty on the academic job market (2024/2025) &#x2757;
        </span>
        
        <br><br>
        👨🏽‍💻 I'm a Ph.D. candidate in Computer Science and Engineering with a focus on Cybersecurity at Louisiana State University (LSU).

        <br><br>
        📚 I conduct research in Cybersecurity, focusing on Internet-scale measurements to characterize and combat malicious activities. I also research and employ advanced machine learning techniques, such as Temporal Graph Neural Networks (TGNN), to detect Advanced Persistent Threats (APT) attacks. Additionally, I investigate vulnerabilities in source and binary code using Large Language Models (LLM) to enhance software security. I contribute to the development of cyber defense training materials and aim to bridge the gap between theory and practical application for the benefit of national security.
        <br><br>
        🎓 Before coming to LSU, I was a Graduate Research Assistant at the Cyber Center for Security and Analytics (CCSA) at the University of Texas at San Antonio. I received a Bachelor’s degree from the Holy Spirit University of Kaslik (USEK) and a Master’s degree from the American University of Beirut (AUB), both in Computer Science.</div>"
        imageUrl: "/JosephKhoury-v2.jpg"
        imageWidth: 190
        imageHeight: 190
        imageTitle: Joseph Khoury
        buttons:
          - name: Publications
            url: /publications/
          - name: Resume/CV
            url: /resume/

    socialIcons:
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=pupjXigAAAAJ&hl=en&oi=ao
        - name: linkedin
          url: https://www.linkedin.com/in/joseph-khoury-313a55125/

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: false
    label:
      text: "Joseph Khoury"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
