baseURL: "https://khouryjoseph.com/"
title: Joseph Khoury
pagination.pagerSize: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

params:
    description: "I am a PhD Candidate in Computer Science and Engineering at Louisiana State University (LSU)."
    author: Joseph Khoury
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Joseph Khoury
          
          subtitle: "<div style='text-align: justify; text-justify: inter-word;'>
        
          <a href='https://ascslab.com' target='_blank'>        
          <img style='display: inline; all: initial;' alt='Static Badge' src='https://img.shields.io/badge/Visit%20my%20lab%27s%20web%20page-ASCSlab.com-brown'>
          </a>
          <br><br>
          
          👨🏽‍💻 I'm a Ph.D. candidate in Computer Science and Engineering with a focus on Cybersecurity at Louisiana State University (LSU).

          <br><br>
          
          📚 I conduct research in Cybersecurity, focusing on Internet-scale measurements to characterize and analyze malicious activities in the wild. I also research and employ advanced machine learning techniques, such as Temporal Graph Neural Networks (TGNN), to detect Lateral Movement in large and dynamic networks. Additionally, I investigate the capabilities of Large Language Models (LLM) in detecting and repairing software security vulnerabilities. Furthermore, I am actively involved in the development of cyber defense training materials, aiming to enhance the security preparedness of cyber forces.
          
          <br><br>
          
          🎓 Before coming to LSU, I was a Graduate Research Assistant at the Cyber Center for Security and Analytics (CCSA) at the University of Texas at San Antonio. I received a Bachelor’s degree from the Holy Spirit University of Kaslik (USEK) and a Master’s degree from the American University of Beirut (AUB), both in Computer Science.</div>"
          
          imageUrl: "/Joseph.jpg"
          imageWidth: 200
          imageHeight: 200
          
          imageTitle: Joseph Khoury
    
    social:
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=pupjXigAAAAJ&hl=en&oi=ao
        - name: linkedin
          url: https://www.linkedin.com/in/joseph-khoury-313a55125/
        # - name: ASCSLab.com
        #   url: https://www.ascslab.com/
    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: false
    label:
      text: "Joseph Khoury"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2