baseURL: "https://khouryjoseph.com/"
title: Joseph Khoury
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Education
      url: /education/
      weight: 2
    - name: Publications
      url: /publications/
      weight: 3
    - name: Teaching
      url: /teaching/
      weight: 4
    - name: Service
      url: /service/
      weight: 5

taxonomies:
    tag: tags

params:
    description: "Tenure-track Assistant Professor of Computer Science at Louisiana State University (LSU)."
    author: Joseph Khoury
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Joseph Khoury, Ph.D.
          
          subtitle: "<div style='text-align: justify; text-justify: inter-word;'>
          
          I am a tenure-track Assistant Professor of Cybersecurity at the <a href='https://www.lsu.edu/eng/cse/' target='_blank'><strong>Division of Computer Science and Engineering (CSE)</strong></a> at <a href='https://www.lsu.edu/' target='_blank'><strong>Louisiana State University (LSU)</strong></a>.

          <br><br>
          
          I conduct research in Cybersecurity, focusing on Internet-scale measurements to characterize and analyze malicious activities in the wild. I also research and employ advanced machine learning techniques, such as Temporal Graph Neural Networks (TGNN), to detect Lateral Movement in large and dynamic networks. Additionally, I investigate the capabilities of Large Language Models (LLM) in detecting and repairing software security vulnerabilities. Furthermore, I am actively involved in the development of cyber defense training materials, aiming to enhance the security preparedness of cyber forces.</div>"
          
          imageUrl: "/Joseph.jpg"
          imageWidth: 200
          imageHeight: 200
          
          imageTitle: Joseph Khoury
          buttons:
            - name: Education
              url: /education/
            - name: Publications
              url: publications/  
            - name: Teaching
              url: teaching/
            - name: Services
              url: service/

    
    socialIcons:
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=en&user=pupjXigAAAAJ&view_op=list_works&sortby=pubdate
        - name: linkedin
          url: https://www.linkedin.com/in/joseph-khoury-ph-d-313a55125/
        - name: ORCID
          url: https://orcid.org/0000-0002-6219-2875

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: false
    label:
      text: "Joseph Khoury"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2